worker_processes auto;

events { worker_connections 1024; }

http {
  server {
    listen 80;

    location /health {
      add_header Content-Type application/json;
      return 200 '{"status":"ok","component":"nginx"}';
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }
  }
}
