worker_processes auto;

events { worker_connections 1024; }

http {
  upstream api_backend {
    server api1:8080;
    server api2:8080;
    keepalive 16
  }

  #/api/instance

  server {
    listen 80;

    location /health {
      add_header Content-Type application/json;
      return 200 '{"status":"ok","component":"nginx"}';
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }

    #Reverse proxy: /api/* -> API Spring Boot... C#... NODE
    location /api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # remove /api antes de manda para backend
      #/api/hello
      #/hello
      rewrite ^/api/(.*)$ /$1 break;       

      proxy_pass http://api_backend;
    }
  }
}
